### ISSUE TITLE
Backend: Direct3D 12

### ISSUE THREAD

**Issue by VTling** [Immediate-Mode-UI/Nuklear#381] opened 2021-12-17 11:05 UTC
Need dx12 hook

**Comment by RobLoach** [comment] 2021-12-19 23:23
I don't think anyone has put together DX12 backend for Nuklear. Open to help on implementation!

**Comment by RobLoach** [comment] 2021-12-22 20:39
Duplicate of https://github.com/Immediate-Mode-UI/Nuklear/issues/83

**Closed by RobLoach** 2021-12-22 20:39 UTC
Labels: Backend
